kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/sigmoid/Projects/real-time-ecommerce-data-platform/data/source
        containerPath: /data/source
