name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -v

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/hsai-rohit/ecommerce-ingestion:${{ github.sha }} \
            -t ghcr.io/hsai-rohit/ecommerce-ingestion:latest \
            .

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/hsai-rohit/ecommerce-ingestion:${{ github.sha }}
          docker push ghcr.io/hsai-rohit/ecommerce-ingestion:latest
